networks:
  chat_network:
    driver: bridge

services:
  mongodb:
    image: mongo
    container_name: mongo_db
    networks:
      - chat_network
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: ofg
      MONGO_INITDB_ROOT_PASSWORD: 153515

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    networks:
      - chat_network
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ofg
      ME_CONFIG_MONGODB_ADMINPASSWORD: 153515
      ME_CONFIG_MONGODB_SERVER: mongodb

volumes:
  mongo: {}
